#!/usr/bin/env bash
#
# see here
# https://github.com/wlard/dotfiles/blob/master/herbstluftwm/autostart

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# Super as mod
Mod=Mod4
Alt=Mod1

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload

# close client
hc keybind $Mod-e close

# focusing clients
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-i cycle_all +1
hc keybind $Mod-u cycle_all -1

# focus
hc keybind $Mod-BackSpace cycle_monitor
# hc keybind $Mod-Shift-c cycle
# hc keybind $Mod-i jumpto urgent

# moving clients
hc keybind $Mod-$Alt-h     shift left
hc keybind $Mod-$Alt-j     shift down
hc keybind $Mod-$Alt-k     shift up
hc keybind $Mod-$Alt-l     shift right

# splitting frames
hc keybind $Mod-n       split   bottom  0.5
hc keybind $Mod-m       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

# layout
hc keybind $Mod-Shift-h  set_layout horizontal
hc keybind $Mod-Shift-v  set_layout vertical
hc keybind $Mod-Shift-g  set_layout grid
hc keybind $Mod-Shift-m  set_layout max

# client layout
hc keybind $Mod-$Alt-space set_attr clients.focus.floating toggle
hc keybind $Mod-$Alt-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized

# layouting
hc keybind $Mod-apostrophe remove
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle # TODO wtf is this?
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-semicolon                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
hc mousebind Mod1-B4 call substitute WID clients.dragged.winid spawn transset-df --inc -i WID 0.05

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )
# TODO: the fuck does 0 do?
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-$Alt-$key" move_index "$i"
    fi
done

# rules
hc rule focus=on     # focus new clients by default

hc rule class=Pavucontrol floating=true floatplacement=center


# hc set frame_border_width 2
hc set always_show_frame true # TODO: ???
# hc set frame_bg_transparent 1
# hc set frame_transparent_width 5
hc set frame_gap 6
# hc set frame_active_opactiy 1
# hc set frame_normal_opacity 0

# theme
NORMAL_DARK='#222222'
NORMAL='#333333'
# ORANGE='#ccaa00'
ORANGE='#FB8C00'
GREEN='#339933'

# hc attr theme.tiling.reset 1
# hc attr theme.floating.reset 1

hc set frame_border_active_color $GREEN
hc set frame_border_normal_color $NORMAL
hc set frame_bg_normal_color $NORMAL_DARK
hc set frame_bg_active_color $NORMAL_DARK

# hc set window_border_active_color $ORANGE
# hc set window_border_normal_color '#00ff00'
# hc set window_border_urgent_color '#00ff00'
# hc set window_border_inner_color '#00ff00'

hc set window_border_inner_width 2
hc set window_border_outer_width 2
hc set window_border_width 4
hc set window_gap 5

# hc attr theme.active.color $ORANGE
# hc attr theme.urgent.color red
# hc attr theme.inner_width 0
# hc attr theme.inner_color white
# hc attr theme.floating.border_width 4
# hc attr theme.floating.outer_width 10
# hc attr theme.floating.outer_color black
# hc attr theme.background_color white #'#141414'

# hc set window_gap 10
# hc set frame_padding 0
# hc set smart_window_surroundings 0
# hc set smart_frame_surroundings 0
# hc set mouse_recenter_gap 0
# hc set focus_follows_mouse 1

# # title
# hc attr theme.title_height 22
# hc attr theme.title_font 'Iosevka Term Slab:pixelsize=20:style=bold'
# # hc attr theme.title_color '#222222'
# hc attr theme.title_depth 6
# hc attr theme.border_width 2

# hc attr theme.outer_width 2
# hc attr theme.inner_width 2
# hc attr theme.outer_color '#666666'

# hc attr theme.normal.title_color '#cccccc'
# hc attr theme.normal.color $NORMAL_DARK

# hc attr theme.active.inner_color $NORMAL_DARK
# hc attr theme.active.outer_color $NORMAL

# # hc attr theme.padding_top 0  # space below the title's baseline (i.e. text depth)
# # hc attr theme.padding_bottom 0  # space below the title's baseline (i.e. text depth)
# # hc attr theme.padding_left 0  # space below the title's baseline (i.e. text depth)
# # hc set tight_decoration false
# # hc set title_color '#ff0000'
# # hc set title_font fixed

# other
hc set focus_follows_mouse true
hc set ellipsis  "...  "



#-----------------------------------------------
# theme
# https://github.com/wlard/dotfiles/blob/master/herbstluftwm/autostart
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color $GREEN
hc set frame_border_width 1
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 0
hc set frame_active_opactiy 1
hc set frame_normal_opacity 0

hc attr theme.active.color $ORANGE
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color red
hc attr theme.inner_width 0
hc attr theme.inner_color white
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'
hc attr theme.background_color white #'#141414'
#-----------------------------------------------

# hc attr theme.inner_width 10
# hc attr theme.normal.outer_color '#00ff00'

#-----------------------------------------------
# Theme customization
hc attr theme.title_height 20
hc attr theme.title_when always
hc attr theme.title_font 'Iosevka Term Slab:pixelsize=18:style=bold'
hc attr theme.title_depth 4  # space below the title's baseline
hc set frame_gap 4
hc attr theme.title_color '#cccccc' # font
hc attr theme.active.title_color '#323232' # font
hc attr theme.normal.title_color '#cccccc' # font
hc attr theme.urgent.title_color '#cc0000' # font

#-----------------------------------------------


# # theme
# hc attr theme.tiling.reset 1
# hc attr theme.floating.reset 1
# hc set frame_border_active_color '#222222'
# hc set frame_border_normal_color '#101010'
# hc set frame_bg_normal_color '#565656'
# hc set frame_bg_active_color '#345F0C'
# hc set frame_border_width 1
# hc set always_show_frame on
# hc set frame_bg_transparent on
# hc set frame_transparent_width 5
# hc set frame_gap 4

# hc attr theme.title_height 17
# hc attr theme.title_when always
# hc attr theme.title_font 'Iosevka Term Slab:pixelsize=18:style=bold'
# hc attr theme.title_depth 4  # space below the title's baseline
# hc attr theme.active.color '#345F0Cef'
# hc attr theme.title_color '#ffffff'
# hc attr theme.normal.color '#323232'
# hc attr theme.urgent.color '#7811A1'
# hc attr theme.tab_color '#1F1F1F'
# hc attr theme.active.tab_color '#2B4F0A' # inactive on inactive frame
# hc attr theme.active.tab_outer_color '#6C8257'
# hc attr theme.active.tab_title_color '#ababab' # font
# hc attr theme.normal.title_color '#898989'
# hc attr theme.inner_width 1
# hc attr theme.inner_color black
# hc attr theme.border_width 3
# hc attr theme.floating.border_width 4
# hc attr theme.floating.outer_width 1
# hc attr theme.floating.outer_color black
# hc attr theme.active.inner_color '#789161'
# hc attr theme.urgent.inner_color '#9A65B0'
# hc attr theme.normal.inner_color '#606060'
# # copy inner color to outer_color
# for state in active urgent normal ; do
#     hc substitute C theme.${state}.inner_color \
#         attr theme.${state}.outer_color C
# done
# hc attr theme.tiling.outer_width 1
# hc attr theme.background_color '#141414'

# hc set window_gap 0
# hc set frame_padding 0
# hc set smart_window_surroundings off
# hc set smart_frame_surroundings on
# hc set mouse_recenter_gap 0
